set_property(DIRECTORY PROPERTY max::external YES)
set_property(DIRECTORY PROPERTY max::glob ON)
project(o2property)
target_compile_options(o2property PUBLIC ${O2MAX_CFLAGS})
target_include_directories(o2property PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/../o2lib")
target_link_libraries(o2property PRIVATE o2max)